version: '3.3'

services:
  app:
    container_name: second-hand-app
    image: ghcr.io/23yong/secondhand:0.0
    ports:
      - 8080:8080
    environment:
      - TZ=Asia/Seoul

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    environment:
      - TZ=Asia/Seoul
