version: '3.3'

services:
  app:
    container_name: novel-park-app
    image: ghcr.io/23yong/secondhand:0.0
    ports:
      - 8080:8080
    environment:
      - TZ=Asia/Seoul

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    depends_on:
      - app

  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    environment:
      - TZ=Asia/Seoul
